Api add migration or creating the tables for db
danielursu/goooplanner-api pull request #4
Opened 2023-07-27 13:19 UTC by Elisei-26

2023-07-27 15:25 UTC, danielursu requested changes

2023-07-27 15:25 UTC, danielursu commented on src/services/user.service.ts
> +		return users;
```suggestion
		return await this.userRepository.find();
```
let's simplify this

2023-07-27 15:25 UTC, danielursu commented on src/services/user.service.ts
> +	}
this was for demo purposes. You can get rid of

2023-07-27 15:25 UTC, danielursu commented on src/app.controller.ts
> +	}
you can delete this

2023-07-28 09:36 UTC, danielursu requested changes

2023-07-28 09:36 UTC, danielursu commented on src/app.controller.ts
>  @Controller()
please add UserController
that will called when you enter /user

@Controller("user")

2023-07-28 09:36 UTC, danielursu commented on src/services/user.service.ts
> +		return await this.userRepository.find();
please add UserMapperService with toDTO() method
that method will transform your entity to a UserDTO interface

2023-07-28 12:44 UTC, danielursu requested changes

2023-07-28 12:44 UTC, danielursu commented on src/app.module.ts
> +import { UserController } from "./user/user.controller";
delete unused imports

2023-07-28 12:44 UTC, danielursu commented on src/user/user.controller.ts
> +@Controller("users")
```suggestion
@Controller("user")
```

2023-07-28 12:44 UTC, danielursu commented on src/user/user.controller.ts
> +	@Get()
```suggestion
	@Get("all")
```

2023-07-28 13:13 UTC, danielursu approved these changes

2023-07-28 13:14 UTC, samuelburaga approved these changes

2023-07-28 13:14 UTC, merged